# Generated by Django 3.2.12 on 2022-02-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'lugar',
                'verbose_name_plural': 'lugares',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edomexa.place')),
            ],
        ),
        migrations.CreateModel(
            name='PostSectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('css_class', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tipo de sección',
                'verbose_name_plural': 'tipos de sección',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'municipio',
                'verbose_name_plural': 'municipios',
            },
        ),
        migrations.CreateModel(
            name='PostSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('index', models.PositiveSmallIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edomexa.postsectiontype')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edomexa.post')),
            ],
            options={
                'verbose_name': 'sección',
                'verbose_name_plural': 'secciones',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edomexa.town'),
        ),
    ]
