# Generated by Django 3.2.12 on 2022-03-21 05:40
from collections import namedtuple

from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# edomexa.migrations.0002_auto_20220224_0235
# edomexa.migrations.0006_auto_20220224_0404

# noinspection DuplicatedCode
def init_post_section_types(apps, schema_editor):
    SectionType = namedtuple('SectionType', 'description css_class')
    section_types = (
        SectionType('title', 'post-section-type-title'),
        SectionType('subtitle', 'post-section-type-subtitle'),
        SectionType('text', 'post-section-type-text'),
        SectionType('image', 'post-section-type-image'),
    )
    PostSectionType = apps.get_model('edomexa', 'PostSectionType')

    for section_type in section_types:
        new_section_type = PostSectionType(description=section_type.description, css_class=section_type.css_class)
        new_section_type.save()


def init_site_sections(apps, schema_editor):
    site_sections = (
        'Turismo',
        'Museos',
        'Negocios',
        'Eventos',
    )

    SiteSection = apps.get_model('edomexa', 'SiteSection')

    for section in site_sections:
        new_section = SiteSection(name=section)
        new_section.save()


class Migration(migrations.Migration):
    replaces = [('edomexa', '0001_initial'), ('edomexa', '0002_auto_20220224_0235'),
                ('edomexa', '0003_auto_20220224_0346'), ('edomexa', '0004_alter_postsection_options'),
                ('edomexa', '0005_sitesection'), ('edomexa', '0006_auto_20220224_0404'),
                ('edomexa', '0007_post_site_section'), ('edomexa', '0008_auto_20220224_0425'),
                ('edomexa', '0009_sitesection_banner_path')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'lugar',
                'verbose_name_plural': 'lugares',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edomexa.place')),
            ],
        ),
        migrations.CreateModel(
            name='PostSectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('css_class', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'tipo de sección',
                'verbose_name_plural': 'tipos de sección',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'municipio',
                'verbose_name_plural': 'municipios',
            },
        ),
        migrations.CreateModel(
            name='PostSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('index', models.PositiveSmallIntegerField()),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edomexa.postsectiontype')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edomexa.post')),
            ],
            options={
                'verbose_name': 'sección',
                'verbose_name_plural': 'secciones',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='edomexa.town'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='postsection',
            constraint=models.UniqueConstraint(fields=('index', 'post'), name='unique_sectionIndex_post'),
        ),
        migrations.AlterModelOptions(
            name='postsection',
            options={'ordering': ('post', 'index'), 'verbose_name': 'sección', 'verbose_name_plural': 'secciones'},
        ),
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'sección del sitio',
                'verbose_name_plural': 'secciones del sitio',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='site_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='edomexa.sitesection'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='sitesection',
            options={'ordering': ('id',), 'verbose_name': 'sección del sitio',
                     'verbose_name_plural': 'secciones del sitio'},
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='sitesection',
            name='banner_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.RunPython(init_post_section_types),
        migrations.RunPython(init_site_sections),
    ]
