# Generated by Django 3.2.12 on 2022-04-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edomexa', '0001_squashed_0009_sitesection_banner_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html_path',
            field=models.CharField(default='', max_length=500, verbose_name='Ruta de html de post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='miniature_path',
            field=models.CharField(default='', max_length=500, verbose_name='Ruta de miniatura'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='', max_length=500, verbose_name='Subtítulo post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Título post'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PostSection',
        ),
        migrations.DeleteModel(
            name='PostSectionType',
        ),
    ]
