# Generated by Django 3.2.12 on 2022-04-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edomexa', '0002_auto_20220420_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='', max_length=250, verbose_name='Resumen post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Subtítulo post'),
        ),
    ]
