# Generated by Django 3.2.12 on 2022-02-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edomexa', '0002_auto_20220224_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='town',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='postsection',
            constraint=models.UniqueConstraint(fields=('index', 'post'), name='unique_sectionIndex_post'),
        ),
    ]
