# Generated by Django 3.2.12 on 2022-02-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edomexa', '0004_alter_postsection_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'sección del sitio',
                'verbose_name_plural': 'secciones del sitio',
            },
        ),
    ]
