# Generated by Django 3.2.12 on 2022-02-24 10:04
from collections import namedtuple

from django.db import migrations


def init_site_sections(apps, schema_editor):
    site_sections = (
        'Turismo',
        'Museos',
        'Negocios',
        'Eventos',
    )

    SiteSection = apps.get_model('edomexa', 'SiteSection')

    for section in site_sections:
        new_section = SiteSection(name=section)
        new_section.save()


class Migration(migrations.Migration):

    dependencies = [
        ('edomexa', '0005_sitesection'),
    ]

    operations = [
        migrations.RunPython(init_site_sections)
    ]
