# Generated by Django 3.2.12 on 2022-02-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edomexa', '0006_auto_20220224_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='site_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='edomexa.sitesection'),
            preserve_default=False,
        ),
    ]
