# Generated by Django 3.2.12 on 2022-02-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edomexa', '0007_post_site_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='sitesection',
            options={'ordering': ('id',), 'verbose_name': 'sección del sitio', 'verbose_name_plural': 'secciones del sitio'},
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
