# Generated by Django 3.2.12 on 2022-03-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edomexa', '0008_auto_20220224_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesection',
            name='banner_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
